backend:
  name: github
  repo: dungchi1681-web/dc-dalat-family
  branch: main
  auth_scope: repo

media_folder: "images"
public_folder: "/images"

collections:
    - name: "pages"
    label: "Quản lý trang chủ"
    files:
            - file: "index.html"
        label: "Nội dung web"
        name: "home"
        fields:
                    - {label: "Tiêu đề web", name: "title", widget: "string"}
                    - label: "Danh sách 13 ảnh"
            name: "photos"
            widget: "list"
            fields:
                            - {label: "Chọn ảnh", name: "src", widget: "image"}    
                            - {label: "Chú thích ảnh", name: "alt", widget: "string"}
