backend:
  name: github
  repo: dungchi1681-web/dc-dalat-family
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
media_folder: static/img
public_folder: /img
collections:
    - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
            - {label: Title, name: title, widget: string}
            - {label: Body, name: body, widget: markdown}
